package org.hci_eu;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.servlet.http.*;

import org.hci_eu.model.Car;
import org.hci_eu.singletons.RegisteringClassesSingleton;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.Objectify;
import com.googlecode.objectify.ObjectifyService;
import com.googlecode.objectify.Query;

@SuppressWarnings("serial")
public class SimpleObjectifyAppServlet extends HttpServlet {
	public void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws IOException {
		RegisteringClassesSingleton.getSingletonObject();
		Objectify ofy = ObjectifyService.begin();
		// Simple create
		Car porsche =  new Car("2FAST", "red");
		ofy.put(porsche);
		    
		resp.setContentType("text/plain");
		resp.getWriter().println("Hello, world");
		resp.getWriter().print("Was the identifier of the car autogenerated? "); // id was autogenerated
		resp.getWriter().println(porsche.id != null);
		// Get it back
		Car fetched1 = ofy.get(Car.class, porsche.id);    // Getting back the car from the database
		resp.getWriter().println("What was the color of the porsche? "+porsche.color );
		// Delete it
		ofy.delete(porsche);
		
		//Let's complicate it a bit.
		// Create
		porsche = new Car("2FAST", "red");
		Car ferrari = new Car("FASTER", "red");
		Car unimog = new Car("2SLOW", "green");
		Car tesla = new Car("2NEW", "blue");
		ofy.put(tesla, unimog, ferrari,porsche);    //varargs; Car[] and Iterable<Car> also work
		
		// Get the data back
		List<Key<Car>> carKeys = new ArrayList<Key<Car>>();
		carKeys.add(new Key<Car>(Car.class, porsche.id));
		carKeys.add(new Key<Car>(Car.class, unimog.id));
		carKeys.add(new Key<Car>(Car.class, tesla.id));
		Map<Key<Car>, Car> fetched2 = ofy.get(carKeys);
		
		Iterator<Key<Car>> carIterator = fetched2.keySet().iterator();
		while (carIterator.hasNext()) {
			Key<Car> code = carIterator.next();
		    resp.getWriter().println(fetched2.get(code).id+"-"+fetched2.get(code).color);
		}
		Car car = ofy.query(Car.class).filter("color", "red").get();
		resp.getWriter().println("the color of the porche is: "+car.color);
		Query<Car> q = ofy.query(Car.class).filter("color", "red");
		//if it prints more than 2 objects, it is because you have executed more than once this servlet
		//DELETE the workspace/name_project/war/WEB-INF/appengine-generated folder
		for (Car car2: q) {
			resp.getWriter().println(car2.toString());
		}
		
	}
}
